# Configuration of generators
# See `make gen-project` task or https://linkml.io/linkml/generators/project-generator.html
---
includes:
  - jsonschema
  - python

generator_args:
  jsonschema:
    mergeimports: true
    include_null: false
    top_class: OAEProject
    title_from: title
  python:
    mergeimports: true

# Unused generators (can be re-enabled as needed):
# excel, owl, markdown, graphql, java, jsonld, jsonldcontext,
# prefixmap, proto, shacl, shex, sqlddl, typescript