---
site_name: OAE Data Protocol
site_url: https://submarine-mrv.github.io/oae-data-protocol
repo_url: https://github.com/submarine-mrv/oae-data-protocol

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: cyan
  features:
    - navigation.sections
    - navigation.expand
    - content.tabs.link

plugins:
  - search
  - mermaid2:
      version: 10.9.0

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

nav:
  - Home: about.md
  - Schema Reference: index.md
  - Classes:
    - Project & Experiment:
      - Project: Project.md
      - Experiment: Experiment.md
      - InSituExperiment: InSituExperiment.md
      - Intervention: Intervention.md
      - Tracer: Tracer.md
      - InterventionWithTracer: InterventionWithTracer.md
      - Model: model.md
    - Dataset:
      - FieldDataset: FieldDataset.md
      - ModelOutputDataset: ModelOutputDataset.md
    - Variables:
      - InSituVariable: InSituVariable.md
      - MeasuredVariable: MeasuredVariable.md
      - CalculatedVariable: CalculatedVariable.md
      - NonMeasuredVariable: NonMeasuredVariable.md
      - DiscretePHVariable: DiscretePHVariable.md
      - DiscreteTAVariable: DiscreteTAVariable.md
      - DiscreteDICVariable: DiscreteDICVariable.md
      - DiscreteCO2Variable: DiscreteCO2Variable.md
      - HPLCVariable: HPLCVariable.md
    - Instruments & Calibration:
      - AnalyzingInstrument: AnalyzingInstrument.md
      - PHInstrument: PHInstrument.md
      - CRMInstrument: CRMInstrument.md
      - CO2GasDetector: CO2GasDetector.md
      - Calibration: Calibration.md
  - Enumerations:
    - ExperimentType: ExperimentType.md
    - VariableType: VariableType.md
    - GenesisType: GenesisType.md
    - SamplingType: SamplingType.md
    - MCDRPathway: MCDRPathway.md
    - FeedstockType: FeedstockType.md
    - DatasetType: DatasetType.md

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
